version: "3.7"

services:
  httpd:
    build:
      context: .
      dockerfile: .docker/httpd/Dockerfile
    volumes:
      - ./app/public:/var/www/public:rw
      #  Enable if debugging of webserver is required:
      #- ./.logs/httpd:/var/log/apache2:rw
    networks:
      default:
        ipv4_address: 172.16.0.2
    # enable if you want to map the container to port 80 of your host
    # so http://localhost:80 will be the address of the
    #ports:
    # - "80:80"

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      args:
        PHP_UID: ${PHP_UID-1000}
        PHP_GID: ${PHP_GID-1000}
        PACKAGIST_USER: ${PACKAGIST_USER-}
        PACKAGIST_TOKEN: ${PACKAGIST_TOKEN-}
    environment:
      DEBUG: "true"
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: "remote_enable=1 remote_host=172.16.0.1 idekey=PHPSTORM profiler_enable=0"
      PHP_IDE_CONFIG: "serverName=container-templates"
    expose:
      - 9000
    volumes:
      - ./app:/var/www:rw
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/custom-php.ini
      - ./.logs/php:/var/log/php:rw
      - ${GITHUB_SSH_KEY}:/home/www-data/.ssh/id_rsa_github:ro
      - ${BITBUCKET_SSH_KEY}:/home/www-data/.ssh/id_rsa_bitbucket:ro
    networks:
      default:
        ipv4_address: 172.16.0.3

  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: db
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
    expose:
      - 3306
    volumes:
      - ./.docker/mariadb/data:/var/lib/mysql:rw
    networks:
      default:
        ipv4_address: 172.16.0.4

  memcached:
    image: memcached:1.5.22-alpine
    command: memcached -m 64 # sets storage capacity to 64M
    expose:
      - 11211
    networks:
      default:
        ipv4_address: 172.16.0.5

  elasticsearch:
    image: elasticsearch:7.6.0
    environment:
      discovery.type: single-node
    expose:
      - 9200
      - 9300
    volumes:
      - ./.docker/elasticsearch/data:/usr/share/elasticsearch/data:rw
    networks:
      default:
        ipv4_address: 172.16.0.6

  kibana:
    image: kibana:7.6.0
    # uncomment if you want to map the port to localhost
    #ports:
    #  - 5601:5601
    networks:
      default:
        ipv4_address: 172.16.0.7

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
