version: "3.7"

services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    environment:
      PHP_UID: ${PHP_UID-1000}
      PHP_GID: ${PHP_GID-1000}
      PACKAGIST_USER: ${PACKAGIST_USER-}
      PACKAGIST_TOKEN: ${PACKAGIST_TOKEN-}
      DEBUG: "true"
    expose:
      - 9000
    volumes:
      - "./app:/var/www:rw"




