version: "3.7"

services:
  httpd:
    build:
      context: .
      dockerfile: .docker/httpd/Dockerfile
    volumes:
      - ./app/public:/var/www/public:rw
      # Enable if debugging of webserver is required:
      #- .docker/httpd/logs:/var/log/apache2:rw
#    ports:
#    - "80:80"
    networks:
      default:
        ipv4_address: 172.16.0.2


  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    environment:
      PHP_UID: ${PHP_UID-1000}
      PHP_GID: ${PHP_GID-1000}
      PACKAGIST_USER: ${PACKAGIST_USER-}
      PACKAGIST_TOKEN: ${PACKAGIST_TOKEN-}
      DEBUG: "true"
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: "remote_enable=1 remote_host=172.16.0.1 idekey=PHPSTORM profiler_enable=0"
      PHP_IDE_CONFIG: "serverName=container-templates"
    expose:
      - 9000
    volumes:
      - ./app:/var/www:rw
    networks:
      default:
        ipv4_address: 172.16.0.3

  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: db
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
    expose:
      - 3306
    volumes:
      - ./.docker/mariadb/data:/var/lib/mysql:rw
    networks:
      default:
        ipv4_address: 172.16.0.4

  memcached:
    image: memcached:1.5.22-alpine
    command: memcached -m 64 # sets storage capacity to 64M
    expose:
      - 11211
    networks:
      default:
        ipv4_address: 172.16.0.5

# 172.16.0.0/12
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
