version: "3.7"

services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    environment:
      PHP_UID: ${PHP_UID-1000}
      PHP_GID: ${PHP_GID-1000}
      PACKAGIST_USER: ${PACKAGIST_USER-}
      PACKAGIST_TOKEN: ${PACKAGIST_TOKEN-}
      DEBUG: "true"
    expose:
      - 9000
    volumes:
      - ./app:/var/www:rw

  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: db
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
    expose:
      - 3306
    volumes:
      - ./.docker/mariadb/data:/var/lib/mysql:rw

  httpd:
    build:
      context: .
      dockerfile: .docker/httpd/Dockerfile
    volumes:
      - ./app/public:/var/www/public:rw
      # Enable if debugging of webserver is required:
      #- .docker/httpd/logs:/var/log/apache2:rw



